version: "3"
services:
  db:
    image: mysql
    environment:
      - MYSQL_DATABASE=loja
      - MYSQL_USER=root
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes

    volume:
      - /home/elias/Documentos/DevOps/Kubernetes/volume_mysql:/var/lib/mysql

  web:
    image: eneves/aplicacao-loja:1.0
    ports:
      - :8080:80
    depends_on:
      - db
