---
- hosts: hmg-noc
  remote_user: elias.neves
  tasks:
     - name: "Instalando Agente Zabbix!"
       yum:
         name: zabbix-agent
         state: present
       become: true
     - name: "Subindo o Agente e colocando no startup do host"
       service:
         name: zabbix-agent
         state: started
         enabled: yes
       become: true
     - name: "Copiando arquivo de configuração do Agente"
       copy:
         src: /home/eliasneves/Documents/DevOps/Ansible/zabbix_agentd.conf
         dest: /etc/zabbix/zabbix_agentd.conf
       become: true
     - name: "Criando arquivo UserParameter e o script"
       file: path=/etc/zabbix/zabbix_agentd.d/userparameter_mongodb.conf state=touch owner=root group=zabbix mode=0744
       file: path=/srv/mongodb.sh state=touch owner=root group=root mode=0777
       become: true
     - name: "Adicionando informações nos arquivos."
       copy:
         src: /home/eliasneves/Documents/DevOps/Ansible/userparameter_mongodb.conf
         dest: /etc/zabbix/zabbix_agentd.d/userparameter_mongodb.conf

         src: /home/eliasneves/Documents/DevOps/Ansible/mongodb.sh
         dest: /srv/mongodb.sh
       become: true
