---
- hosts: 10.0.94.50,10.0.94.51,10.0.94.52
  remote_user: elias.neves
  become: true

  vars:
    server_list: "172.16.65.100,172.16.65.102,172.16.65.103,172.16.65.108"

  tasks:
  - name: Instalando Agente Zabbix e JQ
    yum:
      name: zabbix-agent
      state: present

      name: jq
      state: present


  - name: "Subindo o Agente e colocando no startup do host"
    service:
      name: zabbix-agent
      state: started
      enabled: yes


  - name: "Copiando arquivo de configuração do Agente"
    template:
      src: zabbix_agentd.conf.j2
      dest: /etc/zabbix/zabbix_agentd.conf
      owner: zabbix
      group: zabbix

  - name: "Adicionando informações nos arquivos."
    copy:
      src: files/mongodb.sh
      dest: /srv/mongodb.sh

  - name: "Adicionando informações nos arquivos."
    copy:
      src: files/userparameter_mongodb.conf
      dest: /etc/zabbix/zabbix_agentd.d/userparameter_mongodb.conf

  - name: "Restarting AGENTE"
    service:
      name: zabbix-agent
      state: restarted
