---
- hosts: 10.0.94.50,10.0.94.51,10.0.94.52
  remote_user: elias.neves
  tasks:
     - name: "Removendo Agente Zabbix!"
       yum:
         name: zabbix-agent
         state: absent
       become: true
